version: '3.8'
services:
  reverse-proxy:
    image: 'jc21/nginx-proxy-manager:2.10.1'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
    volumes:
      - ./proxymanager:/data
  wiremock:
    image: 'wiremock/wiremock:2.35.0'
    volumes:
      - ./wiremock:/home/wiremock
    command: [ --verbose ]
  backend:
    build:
      dockerfile: backend/Dockerfile
      args:
        JAR_FILE: backend/target/*.jar


#  nginx:
#    image: 'nginx:alpine'
#    ports:
#      - '90:8081'
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
